#!/usr/bin/bash

#=====================================================================
# general config
#=====================================================================

set $mod Mod4
floating_modifier $mod
set $left s
set $right t
set $up n
set $down r

#=====================================================================
# general shortcuts
#=====================================================================

bindsym $mod+Return exec foot
bindsym $mod+Shift+q kill
bindsym $mod+d exec kickoff
bindsym $mod+Shift+c reload
bindsym $mod+Shift+e exit

#=====================================================================
# Navigation
#=====================================================================

bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws0

#=====================================================================
# Window management
#=====================================================================

bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+m move workspace to output right
bindsym $mod+Shift+b move workspace to output left

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws0

bindsym $mod+k split h
bindsym $mod+h split v
bindsym $mod+f fullscreen toggle
#bindsym $mod+s layout stacking
#bindsym $mod+w layout tabbed
#bindsym $mod+e layout toggle split
bindsym $mod+Shift+space floating toggle
bindsym $mod+a focus parent
bindsym $mod+Shift+minus move scratchpad
bindsym $mod+minus scratchpad show

#=====================================================================
# Workspaces
#=====================================================================

set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9
set $ws0 0

#=====================================================================
# Modes
#=====================================================================

mode "resize" {
    bindsym j resize shrink width 10 px or 10 ppt
    bindsym k resize grow height 10 px or 10 ppt
    bindsym l resize shrink height 10 px or 10 ppt
    bindsym odiaeresis resize grow width 10 px or 10 ppt

    bindsym Left resize shrink width 10 px or 10 ppt
    bindsym Down resize grow height 10 px or 10 ppt
    bindsym Up resize shrink height 10 px or 10 ppt
    bindsym Right resize grow width 10 px or 10 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+w mode "resize"

#=====================================================================
# Visiual config
#=====================================================================

default_border pixel 3

exec swayidle -w \
  timeout 1805 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"'

# green-brown, focus dark
set $cfocused #34626C
set $cfocused_inactive #839B97
set $cunfocused #CFD3CE
set $cfontl #F1F6F9
set $cfontd #000000

client.focused $cfocused $cfocused $cfontl
client.focused_inactive $cfocused_inactive $cfocused_inactive $cfontd
client.unfocused $cunfocused $cunfocused $cfontd

set $gnome-schema org.gnome.desktop.interface

exec_always {
    gsettings set $gnome-schema gtk-theme 'Adapta'
    gsettings set $gnome-schema icon-theme 'Papirus'
    gsettings set $gnome-schema cursor-theme 'Adawaita'
}

#=====================================================================
# IO config
#=====================================================================

input type:keyboard {
  xkb_layout "de,de"
  xkb_variant "neo,"
  xkb_options "grp:ctrl_alt_toggle,grp_led:scrol"
}

output "*" bg {{ background }} fill

{{ outputs }}

#=====================================================================
# Bar config
#=====================================================================

bar {
    position top
    status_command i3status
}

#=====================================================================
# User startup
#=====================================================================

exec_always /home/joru/.screenlayout/wayland.sh

#=====================================================================
# User shortcuts
#=====================================================================

bindsym $mod+o exec --no-startup-id swaylock
bindsym XF86AudioMute exec --no-startup-id pamixer -t
bindsym XF86AudioLowerVolume exec --no-startup-id pamixer -d 5
bindsym XF86AudioRaiseVolume exec --no-startup-id pamixer -i 5
bindsym XF86AudioNext exec --no-startup-id playerctl next
bindsym XF86AudioPrev exec --no-startup-id playerctl prev
bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
bindsym XF86AudioStop exec --no-startup-id playerctl stop
bindsym XF86AudioMicMute exec --no-startup-id amixer set Capture toggle > /dev/null
bindsym XF86MonBrightnessDown exec --no-startup-id light -U 3
bindsym XF86MonBrightnessUp exec --no-startup-id light -A 3
bindsym XF86Calculator exec --no-startup-id foot ipython
#=====================================================================
# Defaults
#=====================================================================

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

include /etc/sway/config.d/*

