[sway.variables]
background = "~/pictures/wallpaper.png"
outputs = """
output DP-3 pos 0 520 res 1920x1080
output DP-2 pos 1920 0 res 3840x1600
"""

bindsyms = ""
startup = ""
workspace_bindings = ""

[waybar.variables]
modules = '["sway/language", "battery", "pulseaudio", "network", "cpu", "memory", "clock", "tray"]'

[foot.variables]
font_size = 12
