[sway.files]
sway = "~/.config/sway/config"

[foot.files]
foot = "~/.config/foot/foot.ini"

[kickoff.files]
kickoff = "~/.config/kickoff/config.toml"

[zsh]
depends = ["shell"]

[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
zsh_aliases = "~/.zsh_aliases"
starship = "~/.config/starship.toml"

[mako.files]
mako = "~/.config/mako/config"

[nvim.files]
nvim = "~/.config/nvim/init.vim"

[shell.files]
bat = "~/.config/bat/config"
