[sway.files]
sway = "~/.config/sway/config"
swaylock = "~/.config/swaylock/config"
"sway.target" = "~/.config/systemd/user/sway.target"
wallpaper = { target = "~/.config/sway/background.png", type = "symbolic" }

[foot.files]
foot = "~/.config/foot/foot.ini"

[kickoff.files]
kickoff = "~/.config/kickoff/config.toml"

[zsh]
depends = ["shell"]

[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
zsh_aliases = "~/.zsh_aliases"
starship = "~/.config/starship.toml"

[mako.files]
mako = "~/.config/mako/config"

[shell.files]
bat = "~/.config/bat/config"

[git.files]
gitconfig = "~/.config/git/config"
"themes.gitconfig" = "~/.config/git/themes.gitconfig"

[js.files]
npmrc = "~/.npmrc"

[helix.files]
helix = "~/.config/helix/config.toml"

[waybar.files]
waybar = "~/.config/waybar"

[i3status.files]
i3status-rs = "~/.config/i3status-rust/config.toml"
i3status-rs-theme = "~/.config/i3status-rust/themes/onedark.toml"
