[sway.files]
sway = "~/.config/sway/config"

[foot.files]
foot = "~/.config/foot/foot.ini"

[kickoff.files]
kickoff = "~/.config/kickoff/config.toml"

[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
